"""TG-state pipeline adapted from Zhang et al. 2019 (eLife) for PFC-HPC.

Subpackage layout:
    fpp.py           - wavelet + theta-phase FPP construction
    clustering.py    - k-means + gravity-based S/M/EF/LF labelling
    validation.py    - intra/inter correlation + cross-validation
    markov.py        - 4-state transition matrices + occurrence
    ppc.py           - LFP-LFP wavelet PPC, conditioned on TG state
    plotting.py      - matplotlib helpers (hot colormap for PPC)
    data_pipeline.py - per-rat ingestion using src.utils.extract_pt_intervals
"""

from .clustering import (
    STATE_NAMES,
    TGClusterResult,
    cluster_fpps_into_tg_states,
    gravity_features,
    sort_clusters_into_states,
    mean_fpp_per_cluster,
    mean_fpp_per_cluster_substate,
)
from .fpp import (
    ANALYSIS_FS,
    FREQUENCIES,
    FPPCollection,
    MORLET_OMEGA0,
    MORLET_N_SIGMA,
    N_PHASE_BINS,
    PHASE_CENTERS_DEG,
    PHASE_CENTERS_RAD,
    THETA_BAND,
    THETA_CYCLE_FREQ_RANGE,
    cycle_fpp,
    extract_theta_cycles,
    fpps_from_lfp_segment,
    fpps_from_segment_with_cycles,
    smoothed_zscored_power,
    theta_unwrapped_phase,
)
from .emd_cycles import (
    DEFAULT_EMD_CONFIG,
    THETA_BAND_HZ,
    THETA_IMF_PREFER,
    AMP_PERCENTILE,
    SegmentCycles,
    choose_theta_imf_index,
    cycles_for_segment,
    cycles_for_session,
    load_default_emd_config,
)
from .cross_region_pac import (
    GAMMA_BANDS,
    N_PHASE_BINS_PAC,
    DEFAULT_N_SHUFFLES,
    DIRECTION_NAMES,
    DIRECTION_NAMES_HPC_ONLY,
    RatPACResult,
    direction_names_for,
    gamma_amplitude_from_imfs,
    gamma_amplitude_from_lfp,
    pac_for_rat,
    phase_shift_null_mi,
    theta_phase_from_imfs,
    tort_modulation_index,
)
from .markov import (
    TransitionResult,
    cycles_in_interval,
    phasic_vs_tonic_transitions,
    transition_from_labelled_runs,
    transitions_by_substate,
)
from .ppc import (
    CrossSpectrumResult,
    StatePPCResult,
    cross_spectrum_for_segment,
    cross_spectrum_with_cycles,
    ppc_from_angles,
    ppc_phase_pooled,
    state_conditioned_ppc,
)
from .validation import (
    IntraInterResult,
    assign_from_reference,
    cross_dataset_accuracy,
    intra_inter_correlation,
    kfold_intra_inter,
    pairwise_cross_dataset,
)

__all__ = [
    "DEFAULT_EMD_CONFIG",
    "THETA_BAND_HZ",
    "THETA_IMF_PREFER",
    "AMP_PERCENTILE",
    "SegmentCycles",
    "choose_theta_imf_index",
    "cycles_for_segment",
    "cycles_for_session",
    "load_default_emd_config",
    "GAMMA_BANDS",
    "N_PHASE_BINS_PAC",
    "DEFAULT_N_SHUFFLES",
    "DIRECTION_NAMES",
    "DIRECTION_NAMES_HPC_ONLY",
    "RatPACResult",
    "direction_names_for",
    "gamma_amplitude_from_imfs",
    "gamma_amplitude_from_lfp",
    "pac_for_rat",
    "phase_shift_null_mi",
    "theta_phase_from_imfs",
    "tort_modulation_index",
    "fpps_from_segment_with_cycles",
    "cross_spectrum_with_cycles",
    "STATE_NAMES",
    "TGClusterResult",
    "cluster_fpps_into_tg_states",
    "gravity_features",
    "sort_clusters_into_states",
    "mean_fpp_per_cluster",
    "mean_fpp_per_cluster_substate",
    "ANALYSIS_FS",
    "FREQUENCIES",
    "FPPCollection",
    "MORLET_OMEGA0",
    "MORLET_N_SIGMA",
    "N_PHASE_BINS",
    "PHASE_CENTERS_DEG",
    "PHASE_CENTERS_RAD",
    "THETA_BAND",
    "THETA_CYCLE_FREQ_RANGE",
    "cycle_fpp",
    "extract_theta_cycles",
    "fpps_from_lfp_segment",
    "smoothed_zscored_power",
    "theta_unwrapped_phase",
    "TransitionResult",
    "cycles_in_interval",
    "phasic_vs_tonic_transitions",
    "transition_from_labelled_runs",
    "transitions_by_substate",
    "CrossSpectrumResult",
    "StatePPCResult",
    "cross_spectrum_for_segment",
    "ppc_from_angles",
    "ppc_phase_pooled",
    "state_conditioned_ppc",
    "IntraInterResult",
    "assign_from_reference",
    "cross_dataset_accuracy",
    "intra_inter_correlation",
    "kfold_intra_inter",
    "pairwise_cross_dataset",
]
